version: "3"
services:
  # Spring Boot Application
  spring-boot-app:
    image: app
    build: ./springboot/app
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root 
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - mysql  

  # MySQL Database
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '0.0.0.0:3306:3306' 
    volumes:
      - demo:/var/lib/mysql  

  front:
    image: front
    build: ./angular-app
    restart: always
    ports:
      - "0.0.0.0:4200:4200"


volumes:
  demo:
